export const provinces = [
  "All of Cambodia",
  "Banteay Meanchey",
  "Battambang",
  "Kampong Cham",
  "Kampong Chhnang",
  "Kampong Speu",
  "Kampong Thom",
  "Kampot",
  "Kandal",
  "Kep",
  "Koh Kong",
  "Kratie",
  "Mondulkiri",
  "Oddar Meanchey",
  "Pailin",
  "Phnom Penh",
  "Preah Sihanouk",
  "Preah Vihear",
  "Prey Veng",
  "Pursat",
  "Ratanakiri",
  "Siem Reap",
  "Stung Treng",
  "Svay Rieng",
  "Takeo",
  "Tboung Khmum",
];

export const tags = [
  "All Types",
  "beach",
  "mountain",
  "museum",
  "temple",
  "night market",
  "waterfall",
  "local",
  "festival",
  "wildlife",
];

export const categories = [
  { label: "Places", value: "place" },
  { label: "Events", value: "event" },
  { label: "Food & Drink", value: "food" },
  { label: "Souvenirs", value: "souvenir" },
];
