export const provinces = [
  "All of Cambodia",
  "Banteay Meanchey",
  "Battambang",
  "Kampong Cham",
  "Kampong Chhnang",
  "Kampong Speu",
  "Kampong Thom",
  "Kampot",
  "Kandal",
  "Kep",
  "Koh Kong",
  "Kratie",
  "Mondulkiri",
  "Oddar Meanchey",
  "Pailin",
  "Phnom Penh",
  "Preah Sihanouk",
  "Preah Vihear",
  "Prey Veng",
  "Pursat",
  "Ratanakiri",
  "Siem Reap",
  "Stung Treng",
  "Svay Rieng",
  "Takeo",
  "Tboung Khmum",
];

export const tags = [
  "All Types",
  "adventure",
  "ancient",
  "art gallery",
  "beach",
  "cultural",
  "family-friendly",
  "historical",
  "international",
  "island",
  "local",
  "mountain",
  "museum",
  "nature",
  "night market",
  "outdoors",
  "religious",
  "romantic",
  "shopping mall",
  "street food",
  "temple",
  "unesco",
  "waterfall",
  "wildlife",
  "village",
  "zoo",
];

export const categories = [
  { label: "Places", value: "place" },
  { label: "Events", value: "event" },
  { label: "Foods", value: "food" },
  { label: "Drinks", value: "drink" },
  { label: "Souvenirs", value: "souvenir" },
];
