import "dotenv/config";
import { db } from "./index";
import { listings, type NewListing } from "./schema";

// Helper function to generate slug from title
function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim();
}

// Sample Listings Data
const sampleListings: NewListing[] = [
  // ========================================
  // PLACES
  // ========================================
  {
    slug: generateSlug("Kampot Pepper Farm"),
    category: "place",
    tags: ["farm", "agriculture", "tour", "kampot"],
    title: "Kampot Pepper Farm",
    titleKh: "កសិដ្ឋាន​ម្រេច​កំពត",
    xpPoints: 50,
    description:
      "Experience the world-famous Kampot pepper plantation. Learn about traditional farming methods and taste the finest peppercorns grown on red soil. Take a guided tour through the farm and discover why Kampot pepper has geographical indication status.",
    province: "Kampong Cham",
    addressText: "Kampot Province, Cambodia",
    lat: 10.6104,
    lng: 104.1886,
    mainImage: "/default-image/place.png",
    priceLevel: "$",
    priceDetails: [
      { label: "Tour & Tasting", price: "5", currency: "USD" },
      { label: "Locals", price: "3", currency: "USD" },
    ],
    operatingHours: {
      monday: [{ open: "08:00", close: "17:00" }],
      tuesday: [{ open: "08:00", close: "17:00" }],
      wednesday: [{ open: "08:00", close: "17:00" }],
      thursday: [{ open: "08:00", close: "17:00" }],
      friday: [{ open: "08:00", close: "17:00" }],
      saturday: [{ open: "08:00", close: "17:00" }],
      sunday: [{ open: "08:00", close: "17:00" }],
    },
    contactInfo: {
      phone: "+855 12 345 678",
      facebook: "https://facebook.com/kampotpepper",
    },
    googlePlaceId: "ChIJ_placeholder_1",
  },
  {
    slug: generateSlug("Battambang Bamboo Train"),
    category: "place",
    tags: ["transport", "adventure", "unique", "battambang"],
    title: "Battambang Bamboo Train",
    titleKh: "រថភ្លើងឬស្សីបាត់ដំបង",
    xpPoints: 40,
    description:
      "Ride the unique bamboo train (Norry) through rice fields and villages. A thrilling journey on bamboo platforms powered by small motors. This iconic Cambodian experience is a must-do when visiting Battambang.",
    province: "Battambang",
    addressText: "O Dambang, Battambang Province, Cambodia",
    lat: 13.0811,
    lng: 103.1991,
    mainImage: "/default-image/event.png",
    priceLevel: "$",
    priceDetails: [{ label: "Round Trip", price: "5", currency: "USD" }],
    operatingHours: {
      monday: [{ open: "07:00", close: "18:00" }],
      tuesday: [{ open: "07:00", close: "18:00" }],
      wednesday: [{ open: "07:00", close: "18:00" }],
      thursday: [{ open: "07:00", close: "18:00" }],
      friday: [{ open: "07:00", close: "18:00" }],
      saturday: [{ open: "07:00", close: "18:00" }],
      sunday: [{ open: "07:00", close: "18:00" }],
    },
    googlePlaceId: "ChIJ_placeholder_2",
  },
  {
    slug: generateSlug("Koh Ker Temple Complex"),
    category: "place",
    tags: ["temple", "ancient", "history", "unesco"],
    title: "Koh Ker Temple Complex",
    titleKh: "ប្រាសាទកោះកេរ",
    xpPoints: 80,
    description:
      "Ancient Khmer temple complex far from tourist crowds. Climb the 7-tiered pyramid for stunning forest views. Built in the 10th century as the capital of the Khmer Empire, Koh Ker offers a mysterious and uncrowded alternative to Angkor Wat.",
    province: "Siem Reap",
    addressText:
      "Srayong Commune, Kulen District, Preah Vihear Province, Cambodia",
    lat: 13.7885,
    lng: 104.5311,
    mainImage: "/default-image/place.png",
    priceLevel: "$$",
    priceDetails: [
      { label: "Foreigners", price: "10", currency: "USD" },
      { label: "Cambodians", price: "5000", currency: "KHR" },
    ],
    operatingHours: {
      monday: [{ open: "07:30", close: "17:30" }],
      tuesday: [{ open: "07:30", close: "17:30" }],
      wednesday: [{ open: "07:30", close: "17:30" }],
      thursday: [{ open: "07:30", close: "17:30" }],
      friday: [{ open: "07:30", close: "17:30" }],
      saturday: [{ open: "07:30", close: "17:30" }],
      sunday: [{ open: "07:30", close: "17:30" }],
    },
    googlePlaceId: "ChIJ_placeholder_3",
  },
  {
    slug: generateSlug("Kampong Phluk Floating Village"),
    category: "place",
    tags: ["village", "lake", "culture", "tonle-sap"],
    title: "Kampong Phluk Floating Village",
    titleKh: "ភូមិអណ្តែតកំពង់ផ្លុក",
    xpPoints: 70,
    description:
      "Traditional stilt village on Tonle Sap Lake. Houses rise up to 10 meters during wet season. Authentic local life experience with boat tours through mangrove forests and the opportunity to see fishermen at work.",
    province: "Siem Reap",
    addressText:
      "Kampong Phluk, Prasat Bakong District, Siem Reap Province, Cambodia",
    lat: 12.8758,
    lng: 104.0514,
    mainImage: "/default-image/place.png",
    priceLevel: "$$",
    priceDetails: [{ label: "Boat Tour", price: "20", currency: "USD" }],
    operatingHours: {
      monday: [{ open: "06:00", close: "18:00" }],
      tuesday: [{ open: "06:00", close: "18:00" }],
      wednesday: [{ open: "06:00", close: "18:00" }],
      thursday: [{ open: "06:00", close: "18:00" }],
      friday: [{ open: "06:00", close: "18:00" }],
      saturday: [{ open: "06:00", close: "18:00" }],
      sunday: [{ open: "06:00", close: "18:00" }],
    },
    googlePlaceId: "ChIJ_placeholder_4",
  },
  {
    slug: generateSlug("Bokor Hill Station"),
    category: "place",
    tags: ["mountain", "history", "colonial", "kampot"],
    title: "Bokor Hill Station",
    titleKh: "ស្ថានីយ៍ភ្នំបូកគោ",
    xpPoints: 65,
    description:
      "Abandoned French colonial hill station shrouded in mist. Eerie atmosphere with old casino and church ruins. The misty mountain climate and ghostly buildings create a unique and mysterious experience.",
    province: "Kampong Cham",
    addressText: "Bokor National Park, Kampot Province, Cambodia",
    lat: 10.6333,
    lng: 104.05,
    mainImage: "/default-image/place.png",
    priceLevel: "Free",
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_5",
  },
  {
    slug: generateSlug("Angkor Wat"),
    category: "place",
    tags: ["temple", "unesco", "angkor", "heritage"],
    title: "Angkor Wat",
    titleKh: "អង្គរវត្ត",
    xpPoints: 100,
    description:
      "The largest religious monument in the world and Cambodia's crown jewel. Built in the 12th century, this magnificent temple complex is a masterpiece of Khmer architecture. Witness breathtaking sunrise views and explore intricate bas-reliefs depicting Hindu epics.",
    province: "Siem Reap",
    addressText: "Angkor Archaeological Park, Siem Reap Province, Cambodia",
    lat: 13.4125,
    lng: 103.867,
    mainImage: "/default-image/place.png",
    priceLevel: "$$$",
    priceDetails: [
      { label: "1-Day Pass", price: "37", currency: "USD" },
      { label: "3-Day Pass", price: "62", currency: "USD" },
      { label: "7-Day Pass", price: "72", currency: "USD" },
    ],
    operatingHours: {
      monday: [{ open: "05:00", close: "17:30" }],
      tuesday: [{ open: "05:00", close: "17:30" }],
      wednesday: [{ open: "05:00", close: "17:30" }],
      thursday: [{ open: "05:00", close: "17:30" }],
      friday: [{ open: "05:00", close: "17:30" }],
      saturday: [{ open: "05:00", close: "17:30" }],
      sunday: [{ open: "05:00", close: "17:30" }],
    },
    googlePlaceId: "ChIJ_placeholder_6",
  },
  {
    slug: generateSlug("Royal Palace Phnom Penh"),
    category: "place",
    tags: ["palace", "royal", "culture", "phnom-penh"],
    title: "Royal Palace Phnom Penh",
    titleKh: "ព្រះបរមរាជវាំងភ្នំពេញ",
    xpPoints: 75,
    description:
      "Official residence of the King of Cambodia. Marvel at the stunning Silver Pagoda with its floor of 5,000 silver tiles. Explore beautiful Khmer architecture, manicured gardens, and witness the grandeur of Cambodian royalty.",
    province: "Phnom Penh",
    addressText: "Sothearos Blvd, Phnom Penh, Cambodia",
    lat: 11.5644,
    lng: 104.9282,
    mainImage: "/default-image/place.png",
    priceLevel: "$$",
    priceDetails: [
      { label: "Foreign Visitors", price: "10", currency: "USD" },
      { label: "Cambodian Citizens", price: "Free", currency: "KHR" },
    ],
    operatingHours: {
      monday: [
        { open: "08:00", close: "11:00" },
        { open: "14:00", close: "17:00" },
      ],
      tuesday: [
        { open: "08:00", close: "11:00" },
        { open: "14:00", close: "17:00" },
      ],
      wednesday: [
        { open: "08:00", close: "11:00" },
        { open: "14:00", close: "17:00" },
      ],
      thursday: [
        { open: "08:00", close: "11:00" },
        { open: "14:00", close: "17:00" },
      ],
      friday: [
        { open: "08:00", close: "11:00" },
        { open: "14:00", close: "17:00" },
      ],
      saturday: [
        { open: "08:00", close: "11:00" },
        { open: "14:00", close: "17:00" },
      ],
      sunday: [
        { open: "08:00", close: "11:00" },
        { open: "14:00", close: "17:00" },
      ],
    },
    contactInfo: {
      phone: "+855 23 430 345",
    },
    googlePlaceId: "ChIJ_placeholder_7",
  },
  {
    slug: generateSlug("Koh Rong Island"),
    category: "place",
    tags: ["island", "beach", "nature", "preah Sihanouk"],
    title: "Koh Rong Island",
    titleKh: "កោះរ៉ុង",
    xpPoints: 85,
    description:
      "Paradise island with pristine white sand beaches and crystal-clear waters. Experience bioluminescent plankton at night, snorkel in coral reefs, or simply relax in beach hammocks. Perfect for digital detox and island life.",
    province: "Preah Sihanouk",
    addressText: "Koh Rong, Preah Sihanouk Province, Cambodia",
    lat: 10.7126,
    lng: 103.2961,
    mainImage: "/default-image/place.png",
    priceLevel: "$$",
    priceDetails: [{ label: "Ferry Round Trip", price: "25", currency: "USD" }],
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_8",
  },

  // ========================================
  // FOOD
  // ========================================
  {
    slug: generateSlug("Fish Amok"),
    category: "food",
    tags: ["traditional", "curry", "seafood", "national-dish"],
    title: "Fish Amok",
    titleKh: "អាម៉ុកត្រី",
    xpPoints: 30,
    description:
      "Cambodia's national dish. Steamed fish mousse with coconut milk, lemongrass, and aromatic spices in banana leaf. The creamy texture and fragrant spices make this a must-try dish that represents the essence of Khmer cuisine.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Restaurants & Street Vendors",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [
      { label: "Street Vendor", price: "3", currency: "USD" },
      { label: "Restaurant", price: "6", currency: "USD" },
    ],
  },
  {
    slug: generateSlug("Beef Lok Lak"),
    category: "food",
    tags: ["beef", "stir-fry", "traditional", "lunch"],
    title: "Beef Lok Lak",
    titleKh: "លក់​ឡក់​សាច់​គោ",
    xpPoints: 25,
    description:
      "Stir-fried marinated beef cubes served with fresh vegetables, rice, and a tangy lime-pepper dipping sauce. Popular lunch dish that's both flavorful and satisfying.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Restaurants",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Average Price", price: "5", currency: "USD" }],
  },
  {
    slug: generateSlug("Nom Banh Chok"),
    category: "food",
    tags: ["noodles", "breakfast", "traditional", "curry"],
    title: "Nom Banh Chok (Khmer Noodles)",
    titleKh: "នំបញ្ចុក",
    xpPoints: 30,
    description:
      "Fresh rice noodles topped with green fish curry gravy and raw vegetables. Traditional breakfast dish beloved by locals. The light yet flavorful curry makes it perfect for starting your day.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Morning Markets & Street Vendors",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Typical Price", price: "1.5", currency: "USD" }],
  },
  {
    slug: generateSlug("Bai Sach Chrouk"),
    category: "food",
    tags: ["pork", "rice", "breakfast", "grilled"],
    title: "Bai Sach Chrouk",
    titleKh: "បាយសាច់ជ្រូក",
    xpPoints: 25,
    description:
      "Grilled marinated pork served over broken rice with pickled vegetables and clear soup. The most popular breakfast dish in Cambodia. The caramelized pork is sweet, savory, and absolutely addictive.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Morning Markets & Street Vendors",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Street Price", price: "2", currency: "USD" }],
  },
  {
    slug: generateSlug("Khmer Red Curry"),
    category: "food",
    tags: ["curry", "traditional", "spicy", "coconut"],
    title: "Khmer Red Curry",
    titleKh: "ការីក្រហម",
    xpPoints: 20,
    description:
      "Rich and aromatic red curry with beef, chicken, or fish, mixed with vegetables, potatoes, and coconut milk. Less spicy than Thai curry but full of complex flavors from lemongrass, galangal, and Khmer spices.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Restaurants",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Average Price", price: "4.5", currency: "USD" }],
  },

  // ========================================
  // DRINKS (now categorized as food)
  // ========================================
  {
    slug: generateSlug("Palm Juice"),
    category: "food",
    tags: ["traditional", "sweet", "natural", "refreshing"],
    title: "Palm Juice (Tuk Tnout Choo)",
    titleKh: "ទឹកត្នោតជ្រូក",
    xpPoints: 10,
    description:
      "Fresh juice from sugar palm trees. Sweet and refreshing with a unique flavor. Best served cold. This traditional drink has been enjoyed for generations and is both delicious and nutritious.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Street Vendors & Markets",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/drink.png",
    priceLevel: "$",
    priceDetails: [{ label: "Street Price", price: "0.75", currency: "USD" }],
  },
  {
    slug: generateSlug("Iced Coffee"),
    category: "food",
    tags: ["coffee", "iced", "traditional", "breakfast"],
    title: "Teuk Krola Paeng (Iced Coffee)",
    titleKh: "ទឹកកាហ្វេប៉េងខ្មៅ",
    xpPoints: 10,
    description:
      "Strong Cambodian iced coffee made with robusta beans and sweetened condensed milk. Incredibly smooth and energizing. The perfect pick-me-up on a hot Cambodian day.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Cafes & Street Vendors",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/drink.png",
    priceLevel: "$",
    priceDetails: [{ label: "Typical Price", price: "1.5", currency: "USD" }],
  },
  {
    slug: generateSlug("Sugarcane Juice"),
    category: "food",
    tags: ["juice", "sweet", "fresh", "natural"],
    title: "Sugarcane Juice (Tuk Ampov)",
    titleKh: "ទឹកអំពៅ",
    xpPoints: 10,
    description:
      "Freshly pressed sugarcane juice, sometimes mixed with lime and kumquat. Natural sweetness with a refreshing citrus twist. Watch vendors press the cane through manual or electric presses.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Street Vendors & Markets",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/drink.png",
    priceLevel: "$",
    priceDetails: [{ label: "Glass", price: "0.5", currency: "USD" }],
  },
  {
    slug: generateSlug("Num Tkak Cho"),
    category: "food",
    tags: ["smoothie", "traditional", "healthy", "breakfast"],
    title: "Num Tkak Cho (Lime Shake)",
    titleKh: "នំត្កាកឈូ",
    xpPoints: 15,
    description:
      "Sweet and tangy shake made with fresh lime, sugar, and ice. Often blended with egg for extra richness. A popular breakfast drink that's both refreshing and energizing.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Drink Stalls",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/drink.png",
    priceLevel: "$",
    priceDetails: [{ label: "Small Cup", price: "1", currency: "USD" }],
  },

  // ========================================
  // SOUVENIRS
  // ========================================
  {
    slug: generateSlug("Krama Traditional Scarf"),
    category: "souvenir",
    tags: ["textile", "traditional", "clothing", "handmade"],
    title: "Krama (Traditional Scarf)",
    titleKh: "ក្រមា",
    xpPoints: 15,
    description:
      "Iconic checkered cotton scarf worn by Cambodians. Multiple uses: headwrap, towel, baby carrier. Various colors available. An essential item in Cambodian culture with countless practical applications.",
    province: "Siem Reap",
    addressText: "Central Market & Old Market, Phnom Penh & Siem Reap",
    lat: 11.5696,
    lng: 104.9251,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$",
    priceDetails: [
      { label: "Basic Cotton", price: "3", currency: "USD" },
      { label: "Premium Quality", price: "8", currency: "USD" },
    ],
  },
  {
    slug: generateSlug("Kampot Pepper"),
    category: "souvenir",
    tags: ["spice", "gourmet", "kampot", "gift"],
    title: "Kampot Pepper",
    titleKh: "ម្រេចកំពត",
    xpPoints: 20,
    description:
      "World-renowned Kampot peppercorns with geographical indication status. Red, black, and white varieties. Considered some of the finest pepper in the world, with a unique aromatic profile.",
    province: "Kampong Cham",
    addressText: "Kampot Province & Specialty Shops Nationwide",
    lat: 10.6104,
    lng: 104.1886,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$$",
    priceDetails: [
      { label: "100g", price: "5", currency: "USD" },
      { label: "500g", price: "15", currency: "USD" },
    ],
  },
  {
    slug: generateSlug("Silk Scarf"),
    category: "souvenir",
    tags: ["silk", "handwoven", "luxury", "traditional"],
    title: "Silk Scarf",
    titleKh: "ក្រមាសូត្រ",
    xpPoints: 25,
    description:
      "Hand-woven silk scarves with traditional patterns. Made in Cambodian silk villages. Luxury quality with intricate designs inspired by ancient Khmer art.",
    province: "Siem Reap",
    addressText: "Silk Villages (Siem Reap) & Markets Nationwide",
    lat: 13.3671,
    lng: 103.8448,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$$",
    priceDetails: [
      { label: "Standard Size", price: "20", currency: "USD" },
      { label: "Premium/Large", price: "60", currency: "USD" },
    ],
  },
  {
    slug: generateSlug("Silver Jewelry"),
    category: "souvenir",
    tags: ["jewelry", "handmade", "silver", "traditional"],
    title: "Cambodian Silver Jewelry",
    titleKh: "គ្រឿងអលង្ការប្រាក់",
    description:
      "Handcrafted silver jewelry featuring traditional Khmer designs. From intricate necklaces to delicate bracelets, each piece tells a story of Cambodian craftsmanship. Many designs incorporate ancient Angkorian motifs.",
    province: "Phnom Penh",
    addressText: "Russian Market, Phnom Penh & Artisan Shops",
    lat: 11.5458,
    lng: 104.9176,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$$",
    priceDetails: [
      { label: "Simple Bracelet", price: "15", currency: "USD" },
      { label: "Elaborate Necklace", price: "50", currency: "USD" },
    ],
  },
  {
    slug: generateSlug("Stone Carving"),
    category: "souvenir",
    tags: ["art", "sculpture", "traditional", "handmade"],
    title: "Angkor Stone Carving",
    titleKh: "ចម្លាក់ថ្មអង្គរ",
    xpPoints: 20,
    description:
      "Miniature replicas of Angkor Wat and other temples, or Buddha statues carved from sandstone. Skilled artisans recreate the intricate details of ancient Khmer architecture in these beautiful keepsakes.",
    province: "Siem Reap",
    addressText: "Artisan Angkor, Siem Reap & Handicraft Markets",
    lat: 13.3622,
    lng: 103.8597,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$$",
    priceDetails: [
      { label: "Small Carving", price: "10", currency: "USD" },
      { label: "Large Piece", price: "100", currency: "USD" },
    ],
  },

  // ========================================
  // ADDITIONAL PLACES
  // ========================================
  {
    slug: generateSlug("Phnom Kulen National Park"),
    category: "place",
    tags: ["nature", "waterfall", "mountain", "sacred"],
    title: "Phnom Kulen National Park",
    titleKh: "ឧទ្យានជាតិភ្នំគូលេន",
    xpPoints: 75,
    description:
      "Sacred mountain with spectacular waterfalls and ancient carvings. Home to the River of a Thousand Lingas with intricate underwater stone carvings. The birthplace of the Khmer Empire with religious significance and natural beauty.",
    province: "Siem Reap",
    addressText: "Svay Leu District, Siem Reap Province, Cambodia",
    lat: 13.5897,
    lng: 104.0153,
    mainImage: "/default-image/place.png",
    priceLevel: "$$",
    priceDetails: [{ label: "Entry Fee", price: "20", currency: "USD" }],
    operatingHours: {
      monday: [{ open: "06:00", close: "17:00" }],
      tuesday: [{ open: "06:00", close: "17:00" }],
      wednesday: [{ open: "06:00", close: "17:00" }],
      thursday: [{ open: "06:00", close: "17:00" }],
      friday: [{ open: "06:00", close: "17:00" }],
      saturday: [{ open: "06:00", close: "17:00" }],
      sunday: [{ open: "06:00", close: "17:00" }],
    },
    googlePlaceId: "ChIJ_placeholder_23",
  },
  {
    slug: generateSlug("Kep Beach"),
    category: "place",
    tags: ["beach", "seafood", "relaxation", "kep"],
    title: "Kep Beach",
    titleKh: "ឆ្នេរកែប",
    xpPoints: 60,
    description:
      "Quiet coastal town famous for fresh crab and laid-back atmosphere. Black sand beach with sunset views over the Gulf of Thailand. Visit the famous Crab Market and enjoy the freshest seafood in Cambodia.",
    province: "Takeo",
    addressText: "Kep Province, Cambodia",
    lat: 10.4833,
    lng: 104.3167,
    mainImage: "/default-image/place.png",
    priceLevel: "$",
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_24",
  },
  {
    slug: generateSlug("Preah Vihear Temple"),
    category: "place",
    tags: ["temple", "unesco", "mountain", "history"],
    title: "Preah Vihear Temple",
    titleKh: "ប្រាសាទព្រះវិហារ",
    xpPoints: 90,
    description:
      "Spectacular temple perched on cliff edge with panoramic views. UNESCO World Heritage Site dating back to 9th century. The dramatic location and stunning architecture make this one of Cambodia's most impressive temples.",
    province: "Phnom Penh",
    addressText: "Preah Vihear Province, Cambodia",
    lat: 14.3903,
    lng: 104.6817,
    mainImage: "/default-image/place.png",
    priceLevel: "$$",
    priceDetails: [{ label: "Entry Fee", price: "10", currency: "USD" }],
    operatingHours: {
      monday: [{ open: "07:30", close: "17:30" }],
      tuesday: [{ open: "07:30", close: "17:30" }],
      wednesday: [{ open: "07:30", close: "17:30" }],
      thursday: [{ open: "07:30", close: "17:30" }],
      friday: [{ open: "07:30", close: "17:30" }],
      saturday: [{ open: "07:30", close: "17:30" }],
      sunday: [{ open: "07:30", close: "17:30" }],
    },
    googlePlaceId: "ChIJ_placeholder_25",
  },
  {
    slug: generateSlug("Bayon Temple"),
    category: "place",
    tags: ["temple", "angkor", "faces", "unesco"],
    title: "Bayon Temple",
    titleKh: "ប្រាសាទបាយ័ន",
    xpPoints: 85,
    description:
      "Famous temple featuring 216 serene stone faces. Built in late 12th century as the state temple of King Jayavarman VII. The enigmatic smiling faces create an unforgettable spiritual atmosphere.",
    province: "Siem Reap",
    addressText: "Angkor Thom, Siem Reap Province, Cambodia",
    lat: 13.4412,
    lng: 103.8589,
    mainImage: "/default-image/place.png",
    priceLevel: "$$$",
    priceDetails: [{ label: "Angkor Pass", price: "37", currency: "USD" }],
    operatingHours: {
      monday: [{ open: "07:30", close: "17:30" }],
      tuesday: [{ open: "07:30", close: "17:30" }],
      wednesday: [{ open: "07:30", close: "17:30" }],
      thursday: [{ open: "07:30", close: "17:30" }],
      friday: [{ open: "07:30", close: "17:30" }],
      saturday: [{ open: "07:30", close: "17:30" }],
      sunday: [{ open: "07:30", close: "17:30" }],
    },
    googlePlaceId: "ChIJ_placeholder_26",
  },
  {
    slug: generateSlug("Ta Prohm Temple"),
    category: "place",
    tags: ["temple", "angkor", "nature", "tomb-raider"],
    title: "Ta Prohm Temple",
    titleKh: "ប្រាសាទតាព្រហ្ម",
    xpPoints: 80,
    description:
      "Jungle temple where massive trees grow through ancient ruins. Famous filming location for Tomb Raider. Nature and architecture merge in this atmospheric temple left partly unrestored.",
    province: "Siem Reap",
    addressText: "Angkor Archaeological Park, Siem Reap Province, Cambodia",
    lat: 13.435,
    lng: 103.8892,
    mainImage: "/default-image/place.png",
    priceLevel: "$$$",
    priceDetails: [{ label: "Angkor Pass", price: "37", currency: "USD" }],
    operatingHours: {
      monday: [{ open: "07:30", close: "17:30" }],
      tuesday: [{ open: "07:30", close: "17:30" }],
      wednesday: [{ open: "07:30", close: "17:30" }],
      thursday: [{ open: "07:30", close: "17:30" }],
      friday: [{ open: "07:30", close: "17:30" }],
      saturday: [{ open: "07:30", close: "17:30" }],
      sunday: [{ open: "07:30", close: "17:30" }],
    },
    googlePlaceId: "ChIJ_placeholder_27",
  },
  {
    slug: generateSlug("Koh Tonsay Rabbit Island"),
    category: "place",
    tags: ["island", "beach", "quiet", "escape"],
    title: "Koh Tonsay (Rabbit Island)",
    titleKh: "កោះតុនស័យ",
    xpPoints: 55,
    description:
      "Peaceful island paradise near Kep with pristine beaches. Basic bungalows and fresh seafood. Perfect for travelers seeking tranquility away from tourist crowds. No electricity in many areas after dark adds to the authentic experience.",
    province: "Takeo",
    addressText: "Off the coast of Kep Province, Cambodia",
    lat: 10.4333,
    lng: 104.35,
    mainImage: "/default-image/place.png",
    priceLevel: "$",
    priceDetails: [{ label: "Boat Transfer", price: "8", currency: "USD" }],
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_28",
  },
  {
    slug: generateSlug("Phnom Penh Central Market"),
    category: "place",
    tags: ["market", "shopping", "architecture", "art-deco"],
    title: "Phnom Penh Central Market (Psar Thmei)",
    titleKh: "ផ្សារថ្មី",
    xpPoints: 40,
    description:
      "Iconic Art Deco market built in 1937. Shop for jewelry, clothing, electronics, and local crafts under the distinctive yellow dome. The central hall specializes in gold and jewelry while outer sections offer everything imaginable.",
    province: "Phnom Penh",
    addressText: "Central Phnom Penh, Cambodia",
    lat: 11.5696,
    lng: 104.9251,
    mainImage: "/default-image/place.png",
    priceLevel: "Free",
    operatingHours: {
      monday: [{ open: "07:00", close: "17:00" }],
      tuesday: [{ open: "07:00", close: "17:00" }],
      wednesday: [{ open: "07:00", close: "17:00" }],
      thursday: [{ open: "07:00", close: "17:00" }],
      friday: [{ open: "07:00", close: "17:00" }],
      saturday: [{ open: "07:00", close: "17:00" }],
      sunday: [{ open: "07:00", close: "17:00" }],
    },
    googlePlaceId: "ChIJ_placeholder_29",
  },
  {
    slug: generateSlug("Banteay Srei Temple"),
    category: "place",
    tags: ["temple", "pink", "detailed", "angkor"],
    title: "Banteay Srei Temple",
    titleKh: "ប្រាសាទបន្ទាយស្រី",
    xpPoints: 75,
    description:
      "Exquisite pink sandstone temple with incredibly detailed carvings. Known as the 'Citadel of Women' for its fine craftsmanship. The intricate bas-reliefs are considered the finest in Cambodia.",
    province: "Siem Reap",
    addressText: "25km from Siem Reap, Cambodia",
    lat: 13.6067,
    lng: 103.9647,
    mainImage: "/default-image/place.png",
    priceLevel: "$$$",
    priceDetails: [{ label: "Angkor Pass", price: "37", currency: "USD" }],
    operatingHours: {
      monday: [{ open: "07:30", close: "17:30" }],
      tuesday: [{ open: "07:30", close: "17:30" }],
      wednesday: [{ open: "07:30", close: "17:30" }],
      thursday: [{ open: "07:30", close: "17:30" }],
      friday: [{ open: "07:30", close: "17:30" }],
      saturday: [{ open: "07:30", close: "17:30" }],
      sunday: [{ open: "07:30", close: "17:30" }],
    },
    googlePlaceId: "ChIJ_placeholder_30",
  },
  {
    slug: generateSlug("Otres Beach"),
    category: "place",
    tags: ["beach", "relaxation", "backpacker", "preah Sihanouk"],
    title: "Otres Beach",
    titleKh: "ឆ្នេរអូទ្រេស",
    xpPoints: 50,
    description:
      "Long stretch of golden sand beach with laid-back vibe. Beachfront restaurants and bungalows. Less crowded than other Preah Sihanouk beaches. Perfect for sunset watching and swimming.",
    province: "Preah Sihanouk",
    addressText: "Preah Sihanouk Province, Cambodia",
    lat: 10.5667,
    lng: 103.5333,
    mainImage: "/default-image/place.png",
    priceLevel: "$",
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_31",
  },
  {
    slug: generateSlug("Tonle Sap Lake"),
    category: "place",
    tags: ["lake", "floating-village", "nature", "culture"],
    title: "Tonle Sap Lake",
    titleKh: "បឹងទន្លេសាប",
    xpPoints: 70,
    description:
      "Southeast Asia's largest freshwater lake. Floating villages and unique ecosystem. The lake expands dramatically during monsoon season. Visit floating schools, markets, and see traditional fishing methods.",
    province: "Phnom Penh",
    addressText: "Central Cambodia",
    lat: 12.8758,
    lng: 104.3667,
    mainImage: "/default-image/place.png",
    priceLevel: "$$",
    priceDetails: [{ label: "Boat Tour", price: "20", currency: "USD" }],
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_32",
  },

  // ========================================
  // ADDITIONAL FOOD
  // ========================================
  {
    slug: generateSlug("Kuy Teav"),
    category: "food",
    tags: ["noodles", "soup", "breakfast", "pork"],
    title: "Kuy Teav",
    titleKh: "គុយទាវ",
    xpPoints: 25,
    description:
      "Rice noodle soup with pork or seafood. Clear broth with fresh herbs and crispy fried garlic. A beloved breakfast dish that's light yet satisfying. Each vendor has their own secret recipe.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Street Vendors & Restaurants",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Bowl", price: "2", currency: "USD" }],
  },
  {
    slug: generateSlug("Khmer BBQ"),
    category: "food",
    tags: ["bbq", "group", "meat", "social"],
    title: "Khmer BBQ",
    titleKh: "អាំងត្រឹង",
    xpPoints: 25,
    description:
      "Interactive grilling experience with dome-shaped grill. Cook marinated meats and vegetables at your table. The central dome grills meat while the outer moat cooks soup. Perfect for groups.",
    province: "Phnom Penh",
    addressText: "Available nationwide - BBQ Restaurants",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$$",
    priceDetails: [{ label: "Per Person", price: "8", currency: "USD" }],
  },
  {
    slug: generateSlug("Lap Khmer"),
    category: "food",
    tags: ["salad", "lime", "beef", "traditional"],
    title: "Lap Khmer",
    titleKh: "ឡាបខ្មែរ",
    xpPoints: 20,
    description:
      "Lime-marinated beef salad with fresh herbs and spices. Thin slices of beef 'cooked' in lime juice. Refreshing and zesty, often eaten with rice. A favorite among locals on hot days.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Restaurants",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Dish", price: "4", currency: "USD" }],
  },
  {
    slug: generateSlug("Samlor Korko"),
    category: "food",
    tags: ["soup", "traditional", "kroeung", "vegetables"],
    title: "Samlor Korko",
    titleKh: "សម្លកកូរ",
    xpPoints: 20,
    description:
      "Traditional stirring soup with roasted rice and kroeung paste. Thick consistency with vegetables and meat or fish. A rustic countryside dish full of authentic flavors and comforting warmth.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Local Restaurants",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Bowl", price: "3.5", currency: "USD" }],
  },
  {
    slug: generateSlug("Nom Pang Pâté"),
    category: "food",
    tags: ["sandwich", "french", "street-food", "breakfast"],
    title: "Nom Pang Pâté (Khmer Sandwich)",
    titleKh: "នំបុ័ងប៉ាតេ",
    xpPoints: 15,
    description:
      "Baguette sandwich with pâté, pickled vegetables, and herbs. French colonial influence meets Khmer flavors. Crispy bread with savory fillings makes for perfect breakfast or snack on the go.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Street Vendors",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Sandwich", price: "1.5", currency: "USD" }],
  },
  {
    slug: generateSlug("Prahok Ktis"),
    category: "food",
    tags: ["dip", "traditional", "pork", "fermented"],
    title: "Prahok Ktis",
    titleKh: "ប្រហុកក្តិស",
    xpPoints: 20,
    description:
      "Creamy dip made with fermented fish paste, pork, and coconut milk. Eaten with fresh vegetables and rice. Strong flavor that's beloved by locals. An essential part of Cambodian cuisine.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Traditional Restaurants",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/food.png",
    priceLevel: "$",
    priceDetails: [{ label: "Serving", price: "4", currency: "USD" }],
  },

  // ========================================
  // ADDITIONAL DRINKS (now categorized as food)
  // ========================================
  {
    slug: generateSlug("Coconut Water"),
    category: "food",
    tags: ["coconut", "fresh", "natural", "refreshing"],
    title: "Fresh Coconut Water (Teuk Doh)",
    titleKh: "ទឹកដូង",
    xpPoints: 10,
    description:
      "Fresh young coconut water straight from the fruit. Naturally sweet and incredibly hydrating. Vendors often chill coconuts in ice carts. After drinking, request the soft coconut meat inside.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Street Vendors",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/drink.png",
    priceLevel: "$",
    priceDetails: [{ label: "Fresh Coconut", price: "1", currency: "USD" }],
  },
  {
    slug: generateSlug("Fruit Shake"),
    category: "food",
    tags: ["smoothie", "fruit", "fresh", "healthy"],
    title: "Cambodian Fruit Shake",
    titleKh: "ទឹកផ្លែឈើ",
    xpPoints: 15,
    description:
      "Blended fruit shakes with ice, milk, and sugar. Choose from mango, dragon fruit, avocado, or mixed fruits. Thick and creamy texture makes these incredibly satisfying on hot days.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Shake Stalls",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/drink.png",
    priceLevel: "$",
    priceDetails: [{ label: "Regular Size", price: "1.5", currency: "USD" }],
  },
  {
    slug: generateSlug("Golden Muscle Wine"),
    category: "food",
    tags: ["wine", "traditional", "herbal", "tonic"],
    title: "Golden Muscle Wine",
    titleKh: "ស្រាសាច់ចំណេញ",
    xpPoints: 15,
    description:
      "Traditional Cambodian rice wine infused with herbs and sometimes snake or scorpion. Believed to have medicinal properties. Popular at celebrations and with BBQ. Strong alcohol content and unique taste.",
    province: "Phnom Penh",
    addressText: "Available at local markets and specialty shops",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/drink.png",
    priceLevel: "$$",
    priceDetails: [{ label: "Bottle", price: "5", currency: "USD" }],
  },
  {
    slug: generateSlug("Angkor Beer"),
    category: "food",
    tags: ["beer", "local", "refreshing", "popular"],
    title: "Angkor Beer",
    titleKh: "ស្រាបៀរអង្គរ",
    xpPoints: 10,
    description:
      "Cambodia's most popular local beer. Light lager perfect for hot weather. Brewed since 1960s with Cambodian water. Pair with any Khmer dish or enjoy ice-cold at the beach.",
    province: "Phnom Penh",
    addressText: "Available nationwide - Restaurants, Bars, Shops",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/drink.png",
    priceLevel: "$",
    priceDetails: [
      { label: "Can/Bottle", price: "1", currency: "USD" },
      { label: "Draft Pint", price: "1.5", currency: "USD" },
    ],
  },

  // ========================================
  // ADDITIONAL SOUVENIRS
  // ========================================
  {
    slug: generateSlug("Khmer Ceramics"),
    category: "souvenir",
    tags: ["pottery", "handmade", "traditional", "decor"],
    title: "Khmer Ceramics",
    titleKh: "គ្រឿងស្មូរខ្មែរ",
    xpPoints: 20,
    description:
      "Traditional pottery with ancient Khmer designs. From decorative vases to functional bowls. Many pieces feature celadon glaze reminiscent of ancient Angkorian ceramics. Each piece tells a story of Cambodia's ceramic heritage.",
    province: "Siem Reap",
    addressText: "Artisan Workshops, Siem Reap & Phnom Penh",
    lat: 13.3622,
    lng: 103.8597,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$$",
    priceDetails: [
      { label: "Small Bowl", price: "8", currency: "USD" },
      { label: "Large Vase", price: "40", currency: "USD" },
    ],
  },
  {
    slug: generateSlug("Bamboo Handicrafts"),
    category: "souvenir",
    tags: ["bamboo", "eco-friendly", "handmade", "traditional"],
    title: "Bamboo Handicrafts",
    titleKh: "សិប្បកម្មឬស្សី",
    xpPoints: 15,
    description:
      "Woven bamboo products from baskets to decorative items. Sustainable and eco-friendly crafts made by skilled artisans. Includes sticky rice containers, lampshades, and traditional rice baskets. Lightweight and perfect for travel.",
    province: "Phnom Penh",
    addressText: "Markets Nationwide & Handicraft Centers",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$",
    priceDetails: [
      { label: "Small Item", price: "5", currency: "USD" },
      { label: "Large Basket", price: "20", currency: "USD" },
    ],
  },
  {
    slug: generateSlug("Apsara Dancing Figurines"),
    category: "souvenir",
    tags: ["art", "sculpture", "traditional", "dance"],
    title: "Apsara Dancing Figurines",
    titleKh: "រូបចម្លាក់អប្សរា",
    xpPoints: 20,
    description:
      "Beautiful figurines depicting traditional Apsara dancers. Made from resin, wood, or metal. Captures the elegant hand gestures and ornate costumes of classical Khmer dance. Available in various sizes and finishes.",
    province: "Phnom Penh",
    addressText: "Souvenir Shops & Markets Nationwide",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$$",
    priceDetails: [
      { label: "Small Figurine", price: "10", currency: "USD" },
      { label: "Large Statue", price: "50", currency: "USD" },
    ],
  },
  {
    slug: generateSlug("Lotus Silk Products"),
    category: "souvenir",
    tags: ["silk", "luxury", "rare", "eco-friendly"],
    title: "Lotus Silk Products",
    titleKh: "សូត្រផ្កាឈូក",
    xpPoints: 30,
    description:
      "Rare fabric made from lotus flower stems. One of the world's most expensive natural textiles. Eco-friendly and incredibly soft. Available as scarves, shawls, and clothing. A truly unique Cambodian product.",
    province: "Siem Reap",
    addressText: "Specialty Shops, Siem Reap & Phnom Penh",
    lat: 13.3622,
    lng: 103.8597,
    mainImage: "/default-image/souvenir.png",
    priceLevel: "$$$",
    priceDetails: [
      { label: "Small Scarf", price: "100", currency: "USD" },
      { label: "Large Shawl", price: "300", currency: "USD" },
    ],
  },

  // ========================================
  // EVENTS
  // ========================================
  {
    slug: generateSlug("Water Festival"),
    category: "event",
    tags: ["festival", "boat-race", "november", "celebration"],
    title: "Water Festival (Bon Om Touk)",
    titleKh: "បុណ្យអុំទូក",
    xpPoints: 50,
    description:
      "Cambodia's largest festival celebrating the reversal of Tonle Sap River. Three days of boat races, concerts, and celebrations in Phnom Penh. Millions gather to watch traditional longboat races. Spectacular fireworks and festive atmosphere.",
    province: "Phnom Penh",
    addressText: "Sisowath Quay, Phnom Penh",
    lat: 11.5625,
    lng: 104.9305,
    mainImage: "/default-image/event.png",
    priceLevel: "Free",
    operatingHours: {
      monday: [{ open: "00:00", close: "23:59" }],
      tuesday: [{ open: "00:00", close: "23:59" }],
      wednesday: [{ open: "00:00", close: "23:59" }],
    },
    googlePlaceId: "ChIJ_placeholder_33",
  },
  {
    slug: generateSlug("Khmer New Year"),
    category: "event",
    tags: ["new-year", "traditional", "april", "celebration"],
    title: "Khmer New Year (Choul Chnam Thmey)",
    titleKh: "ចូលឆ្នាំថ្មី",
    xpPoints: 50,
    description:
      "Cambodia's most important holiday celebrating the end of harvest season. Three days of temple visits, traditional games, and family gatherings. Water splashing festivities similar to Thai Songkran. Experience authentic Cambodian culture and traditions.",
    province: "Siem Reap",
    addressText: "Nationwide, especially in Siem Reap & Phnom Penh",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/event.png",
    priceLevel: "Free",
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_34",
  },
  {
    slug: generateSlug("Pchum Ben Festival"),
    category: "event",
    tags: ["festival", "religious", "buddhist", "ancestors"],
    title: "Pchum Ben (Ancestors' Day)",
    titleKh: "បុណ្យភ្ជុំបិណ្ឌ",
    xpPoints: 40,
    description:
      "15-day Buddhist festival honoring deceased ancestors. Cambodians visit pagodas to make offerings and pray for their ancestors. Peak celebrations during the final three days. Witness deep spiritual devotion and Khmer Buddhist traditions.",
    province: "Phnom Penh",
    addressText: "Pagodas Nationwide",
    lat: 11.5564,
    lng: 104.9282,
    mainImage: "/default-image/event.png",
    priceLevel: "Free",
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_35",
  },
  {
    slug: generateSlug("Angkor Sankranta"),
    category: "event",
    tags: ["festival", "culture", "siem-reap", "traditional"],
    title: "Angkor Sankranta",
    titleKh: "សង្រ្កាន្តអង្គរ",
    xpPoints: 45,
    description:
      "Cultural festival celebrating Khmer New Year in Siem Reap. Traditional performances, exhibitions, and games near Angkor Wat. Experience classical Apsara dance, shadow puppetry, and traditional music. Three days of cultural immersion and entertainment.",
    province: "Siem Reap",
    addressText: "Angkor Wat Area, Siem Reap",
    lat: 13.4125,
    lng: 103.867,
    mainImage: "/default-image/event.png",
    priceLevel: "Free",
    operatingHours: {},
    googlePlaceId: "ChIJ_placeholder_36",
  },
];

async function seed() {
  console.log("🌱 Starting database seed...");

  try {
    // Clear existing listings first
    console.log("🗑️  Clearing existing listings...");
    await db.delete(listings);
    console.log("✅ Cleared existing data");

    // Insert Listings
    console.log("📍 Seeding listings...");
    await db.insert(listings).values(sampleListings);
    console.log(`✅ Inserted ${sampleListings.length} listings`);

    console.log("\n🎉 Seed completed successfully!");
    console.log("\n📝 Next step: Create first admin user");
    console.log("   After signing in with Google, run this SQL command:");
    console.log(
      "   UPDATE users SET role = 'admin' WHERE email = 'your@email.com';\n"
    );
  } catch (error) {
    console.error("❌ Seed failed:", error);
    throw error;
  }
}

seed()
  .catch((error) => {
    console.error("Seed process failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    console.log("🔚 Seed process finished");
    process.exit(0);
  });
